export const eventStatuses = [
  "Draft",
  "Upcoming",
  "Ongoing",
  "Completed",
  "Cancelled",
];

export const eventTypes = [
  "Tournament",
  "Training",
  "Tryout",
  "Competition",
  "Seminar",
  "Fitness Test",
  "Team Meeting",
  "Other",
];

export const sportCategories = [
  "Basketball",
  "Volleyball",
  "Football",
  "Athletics",
  "Swimming",
  "Badminton",
  "Table Tennis",
  "Taekwondo",
  "Chess",
  "Other",
];

export const participationStatuses = [
  "Assigned",
  "Confirmed",
  "Attended",
  "Absent",
  "Excused",
  "Completed",
];

export const athletePool = [
  {
    id: "ATH-2026-001",
    name: "Miguel Dela Cruz",
    studentId: "2026-00124",
    sport: "Basketball",
    team: "Blue Eagles Men",
    yearLevel: "3rd Year",
    role: "Point Guard",
    participationStatus: "Confirmed",
  },
  {
    id: "ATH-2026-002",
    name: "Patricia Gomez",
    studentId: "2025-00319",
    sport: "Volleyball",
    team: "Blue Eagles Women",
    yearLevel: "2nd Year",
    role: "Setter",
    participationStatus: "Assigned",
  },
  {
    id: "ATH-2026-003",
    name: "Lance Navarro",
    studentId: "2024-00781",
    sport: "Football",
    team: "Blue Eagles Football",
    yearLevel: "4th Year",
    role: "Midfielder",
    participationStatus: "Attended",
  },
  {
    id: "ATH-2026-004",
    name: "Celine Ramos",
    studentId: "2026-00416",
    sport: "Athletics",
    team: "Track and Field",
    yearLevel: "1st Year",
    role: "100m Sprinter",
    participationStatus: "Completed",
  },
  {
    id: "ATH-2026-005",
    name: "Joshua Lim",
    studentId: "2023-00211",
    sport: "Swimming",
    team: "Blue Eagles Aquatics",
    yearLevel: "4th Year",
    role: "Freestyle",
    participationStatus: "Confirmed",
  },
  {
    id: "ATH-2026-006",
    name: "Andrea Sy",
    studentId: "2025-00608",
    sport: "Badminton",
    team: "Blue Eagles Racquet",
    yearLevel: "2nd Year",
    role: "Singles",
    participationStatus: "Excused",
  },
  {
    id: "ATH-2026-007",
    name: "Noah Tan",
    studentId: "2026-00267",
    sport: "Taekwondo",
    team: "Blue Eagles Combat",
    yearLevel: "1st Year",
    role: "Kyorugi",
    participationStatus: "Assigned",
  },
  {
    id: "ATH-2026-008",
    name: "Sophia Reyes",
    studentId: "2024-00542",
    sport: "Chess",
    team: "Blue Eagles Mind Sports",
    yearLevel: "3rd Year",
    role: "Board 1",
    participationStatus: "Attended",
  },
];

export const mockEvents = [
  {
    id: "EVT-2601",
    title: "Pre-Season Basketball Combine",
    type: "Fitness Test",
    sportCategory: "Basketball",
    status: "Upcoming",
    venue: "Main Gym Performance Lab",
    organizer: "Coach David Reyes",
    description:
      "Physical benchmarks and movement screening for varsity basketball prospects ahead of the pre-season training block.",
    notes: "Coordinate with strength and conditioning staff for split testing stations.",
    startDate: "2026-05-18",
    endDate: "2026-05-18",
    startTime: "08:00",
    endTime: "12:00",
    maxParticipants: 24,
    assignedAthletes: [
      {
        athleteId: "ATH-2026-001",
        participationStatus: "Confirmed",
        attendanceStatus: "Pending",
        performanceRating: "Pending",
        result: "Pending",
        scoreStatistics: "Pending",
        coachRemarks: "Initial lead guard candidate.",
        strengthsObserved: "Game pace and court vision.",
        areasForImprovement: "Lateral quickness.",
        injuryNotes: "None reported.",
        evaluatedBy: "Coach David Reyes",
        evaluationDate: "2026-05-18",
        metrics: [
          {
            name: "Sprint time",
            value: "12.4",
            unit: "seconds",
            notes: "Baseline 100m split",
          },
          {
            name: "Vertical jump",
            value: "67",
            unit: "cm",
            notes: "Standing vertical",
          },
        ],
      },
      {
        athleteId: "ATH-2026-004",
        participationStatus: "Assigned",
        attendanceStatus: "Pending",
        performanceRating: "Pending",
        result: "Pending",
        scoreStatistics: "Pending",
        coachRemarks: "Shared session for sprint comparison.",
        strengthsObserved: "Strong acceleration profile.",
        areasForImprovement: "Upper body endurance.",
        injuryNotes: "None.",
        evaluatedBy: "Coach David Reyes",
        evaluationDate: "2026-05-18",
        metrics: [
          {
            name: "Sprint time",
            value: "11.9",
            unit: "seconds",
            notes: "Flying start trial",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2602",
    title: "Women’s Volleyball Tactical Session",
    type: "Training",
    sportCategory: "Volleyball",
    status: "Ongoing",
    venue: "Fr. Godofredo Alingal Gym",
    organizer: "Coach Sarah Lim",
    description:
      "Rotation discipline, reception patterns, and late-set communication work for the women’s volleyball squad.",
    notes: "Film breakdown follows immediately after court session.",
    startDate: "2026-05-14",
    endDate: "2026-05-14",
    startTime: "15:00",
    endTime: "18:00",
    maxParticipants: 18,
    assignedAthletes: [
      {
        athleteId: "ATH-2026-002",
        participationStatus: "Attended",
        attendanceStatus: "Present",
        performanceRating: "8.5/10",
        result: "Rotation unit lead",
        scoreStatistics: "Serve receive efficiency 86%",
        coachRemarks: "Held the second unit together during pressure reps.",
        strengthsObserved: "Composure and quick reads.",
        areasForImprovement: "Transition footwork.",
        injuryNotes: "Left shoulder taped, cleared for full session.",
        evaluatedBy: "Coach Sarah Lim",
        evaluationDate: "2026-05-14",
        metrics: [
          {
            name: "Serve receive",
            value: "86",
            unit: "%",
            notes: "Target above 80%",
          },
          {
            name: "Assist quality",
            value: "18",
            unit: "sets",
            notes: "Above session average",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2603",
    title: "University Open Football Tryouts",
    type: "Tryout",
    sportCategory: "Football",
    status: "Draft",
    venue: "Upper Football Pitch",
    organizer: "Coach Marco Alarcon",
    description:
      "Scouting-focused open tryout to identify incoming student-athletes for the next collegiate season.",
    notes: "Medical clearance booth still pending assignment.",
    startDate: "2026-05-23",
    endDate: "2026-05-23",
    startTime: "06:30",
    endTime: "11:30",
    maxParticipants: 60,
    assignedAthletes: [
      {
        athleteId: "ATH-2026-003",
        participationStatus: "Assigned",
        attendanceStatus: "Pending",
        performanceRating: "Pending",
        result: "Pending",
        scoreStatistics: "Pending",
        coachRemarks: "Current varsity player assisting with drills.",
        strengthsObserved: "Leadership presence.",
        areasForImprovement: "N/A",
        injuryNotes: "None.",
        evaluatedBy: "Coach Marco Alarcon",
        evaluationDate: "2026-05-23",
        metrics: [
          {
            name: "Drill stations led",
            value: "3",
            unit: "stations",
            notes: "Support role",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2604",
    title: "Inter-Schools Swimming Invitational",
    type: "Competition",
    sportCategory: "Swimming",
    status: "Completed",
    venue: "Ateneo Aquatics Center",
    organizer: "Coach Isabel Torres",
    description:
      "Regional invitational meet featuring partner schools and timed race evaluations for returning swimmers.",
    notes: "Archive official heat sheets with final summary report.",
    startDate: "2026-05-10",
    endDate: "2026-05-10",
    startTime: "09:00",
    endTime: "17:00",
    maxParticipants: 32,
    assignedAthletes: [
      {
        athleteId: "ATH-2026-005",
        participationStatus: "Completed",
        attendanceStatus: "Present",
        performanceRating: "9/10",
        result: "2nd Place - 100m Freestyle",
        scoreStatistics: "54.11 seconds",
        coachRemarks: "Strong finish and disciplined pacing.",
        strengthsObserved: "Turn efficiency and closing speed.",
        areasForImprovement: "Start reaction time.",
        injuryNotes: "No concerns.",
        evaluatedBy: "Coach Isabel Torres",
        evaluationDate: "2026-05-10",
        metrics: [
          {
            name: "100m freestyle",
            value: "54.11",
            unit: "seconds",
            notes: "Season best",
          },
          {
            name: "Reaction time",
            value: "0.72",
            unit: "seconds",
            notes: "Needs trimming",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2605",
    title: "Athlete Leadership and Wellness Seminar",
    type: "Seminar",
    sportCategory: "Other",
    status: "Cancelled",
    venue: "Athletics Conference Hall",
    organizer: "Office of Student Formation",
    description:
      "Seminar on athlete wellness, captaincy standards, and balancing academic and athletic responsibilities.",
    notes: "Cancelled due to speaker travel disruption. Reschedule in June.",
    startDate: "2026-05-12",
    endDate: "2026-05-12",
    startTime: "13:30",
    endTime: "16:00",
    maxParticipants: 80,
    assignedAthletes: [
      {
        athleteId: "ATH-2026-008",
        participationStatus: "Excused",
        attendanceStatus: "Excused",
        performanceRating: "N/A",
        result: "Session cancelled",
        scoreStatistics: "N/A",
        coachRemarks: "Rebook when new date is confirmed.",
        strengthsObserved: "N/A",
        areasForImprovement: "N/A",
        injuryNotes: "N/A",
        evaluatedBy: "Office of Student Formation",
        evaluationDate: "2026-05-12",
        metrics: [],
      },
    ],
  },
];
