export const eventStatuses = [
  "Draft",
  "Scheduled",
  "Ongoing",
  "Completed",
  "Cancelled",
];

export const resultStatuses = [
  "Not Started",
  "Pending Results",
  "Results Recorded",
  "Published",
];

export const visibilityStatuses = ["Private", "Public"];

export const eventTypes = [
  "Tournament",
  "Training",
  "Tryout",
  "Competition",
  "Seminar",
  "Fitness Test",
  "Team Meeting",
  "Outreach Event",
  "Other",
];

export const sportCategories = [
  "Basketball",
  "Volleyball",
  "Football",
  "Athletics",
  "Swimming",
  "Badminton",
  "Table Tennis",
  "Taekwondo",
  "Chess",
  "Other",
];

export const participationStatuses = [
  "Assigned",
  "Confirmed",
  "Participated",
  "Absent",
  "Excused",
  "Completed",
];

export const currentRole = "Staff/Admin";

export const athletePool = [
  {
    id: "ATH-2026-001",
    name: "Miguel Dela Cruz",
    studentId: "2026-00124",
    sport: "Basketball",
    team: "Blue Eagles Men",
    yearLevel: "3rd Year",
    role: "Point Guard",
  },
  {
    id: "ATH-2026-002",
    name: "Patricia Gomez",
    studentId: "2025-00319",
    sport: "Volleyball",
    team: "Blue Eagles Women",
    yearLevel: "2nd Year",
    role: "Setter",
  },
  {
    id: "ATH-2026-003",
    name: "Lance Navarro",
    studentId: "2024-00781",
    sport: "Football",
    team: "Blue Eagles Football",
    yearLevel: "4th Year",
    role: "Midfielder",
  },
  {
    id: "ATH-2026-004",
    name: "Celine Ramos",
    studentId: "2026-00416",
    sport: "Athletics",
    team: "Track and Field",
    yearLevel: "1st Year",
    role: "100m Sprinter",
  },
  {
    id: "ATH-2026-005",
    name: "Joshua Lim",
    studentId: "2023-00211",
    sport: "Swimming",
    team: "Blue Eagles Aquatics",
    yearLevel: "4th Year",
    role: "Freestyle",
  },
  {
    id: "ATH-2026-006",
    name: "Andrea Sy",
    studentId: "2025-00608",
    sport: "Badminton",
    team: "Blue Eagles Racquet",
    yearLevel: "2nd Year",
    role: "Singles",
  },
  {
    id: "ATH-2026-007",
    name: "Noah Tan",
    studentId: "2026-00267",
    sport: "Taekwondo",
    team: "Blue Eagles Combat",
    yearLevel: "1st Year",
    role: "Kyorugi",
  },
  {
    id: "ATH-2026-008",
    name: "Sophia Reyes",
    studentId: "2024-00542",
    sport: "Chess",
    team: "Blue Eagles Mind Sports",
    yearLevel: "3rd Year",
    role: "Board 1",
  },
  {
    id: "ATH-2026-009",
    name: "Bianca Villanueva",
    studentId: "2025-00911",
    sport: "Table Tennis",
    team: "Blue Eagles Paddle",
    yearLevel: "2nd Year",
    role: "Doubles",
  },
  {
    id: "ATH-2026-010",
    name: "Rafael Santos",
    studentId: "2024-00177",
    sport: "Basketball",
    team: "Blue Eagles Men",
    yearLevel: "3rd Year",
    role: "Forward",
  },
];

const defaultEventEnhancements = {
  "EVT-2601": {
    callTime: "07:15",
    scheduleNotes: "Stations open 30 minutes before testing. Medical clearance desk starts at 7:30 AM.",
    publicNotes: ["Closed department testing session for approved basketball participants."],
    internalNoteEntries: [
      {
        id: "NOTE-EVT-2601-1",
        title: "Testing logistics",
        visibility: "Internal",
        body: "Assign one staff member to each station and keep raw sheets in the performance lab.",
        author: "Athletics Admin",
        createdAt: "2026-05-13T09:15:00",
      },
    ],
    activityLog: ["2026-05-13 - Draft checklist reviewed by strength and conditioning."],
  },
  "EVT-2602": {
    callTime: "14:30",
    scheduleNotes: "Court setup and film equipment check before warmups.",
    publicNotes: ["Varsity-only tactical session."],
    internalNoteEntries: [
      {
        id: "NOTE-EVT-2602-1",
        title: "Load monitoring",
        visibility: "Internal",
        body: "Track shoulder load for setters and liberos during late-set drills.",
        author: "Coach Sarah Lim",
        createdAt: "2026-05-14T08:45:00",
      },
    ],
    activityLog: ["2026-05-14 - Session opened and initial rotation notes recorded."],
  },
  "EVT-2604": {
    callTime: "08:00",
    scheduleNotes: "Official warmup starts at 8:30 AM. Heat sheets must be archived after awards.",
    publicNotes: ["Published results are available for public review."],
    internalNoteEntries: [
      {
        id: "NOTE-EVT-2604-1",
        title: "Archive packet",
        visibility: "Internal",
        body: "Attach timing sheets and podium photos once document storage is connected.",
        author: "Coach Isabel Torres",
        createdAt: "2026-05-11T10:20:00",
      },
    ],
    activityLog: ["2026-05-11 - Results published after timing sheet verification."],
  },
  "EVT-2606": {
    callTime: "06:15",
    scheduleNotes: "Track opens early for warmups. Confirm timing system calibration before first heat.",
    publicNotes: ["Official qualifiers will be visible after results are published."],
    internalNoteEntries: [
      {
        id: "NOTE-EVT-2606-1",
        title: "Timing verification",
        visibility: "Internal",
        body: "Compare timing sheet against manual backup before publication.",
        author: "Coach Marcus Thorne",
        createdAt: "2026-05-09T16:30:00",
      },
    ],
    activityLog: ["2026-05-09 - Results recorded locally; publication pending verification."],
  },
};

const eventRecords = [
  {
    id: "EVT-2601",
    title: "Pre-Season Basketball Combine",
    type: "Fitness Test",
    sportCategory: "Basketball",
    status: "Scheduled",
    visibility: "Private",
    resultStatus: "Not Started",
    venue: "Main Gym Performance Lab",
    organizer: "Coach David Reyes",
    description:
      "Physical benchmarks and movement screening for varsity basketball prospects ahead of the pre-season training block.",
    publicDescription:
      "A controlled athletics department testing session for basketball program preparation.",
    internalNotes:
      "Coordinate split testing stations with strength and conditioning. Medical clearance desk required.",
    startDate: "2026-05-18",
    endDate: "2026-05-18",
    startTime: "08:00",
    endTime: "12:00",
    maxParticipants: 24,
    publishedAt: "",
    overallResult: "",
    winner: "",
    teamResult: "",
    resultVisibility: "Internal Only",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-001",
        participationStatus: "Confirmed",
        attendanceStatus: "Pending",
        resultStatus: "Not Started",
        placement: "Pending",
        scoreStatistics: "Pending",
        performanceNotes: "Initial lead guard candidate.",
        coachRemarks: "Monitor lateral quickness and court-read speed.",
        evaluatedBy: "Coach David Reyes",
        evaluationDate: "2026-05-18",
        metrics: [
          {
            name: "Sprint time",
            value: "Pending",
            unit: "seconds",
            notes: "Baseline 100m split",
          },
          {
            name: "Vertical jump",
            value: "Pending",
            unit: "cm",
            notes: "Standing vertical",
          },
        ],
      },
      {
        athleteId: "ATH-2026-010",
        participationStatus: "Assigned",
        attendanceStatus: "Pending",
        resultStatus: "Not Started",
        placement: "Pending",
        scoreStatistics: "Pending",
        performanceNotes: "Forward strength profile to be established.",
        coachRemarks: "Compare agility with returners.",
        evaluatedBy: "Coach David Reyes",
        evaluationDate: "2026-05-18",
        metrics: [],
      },
    ],
  },
  {
    id: "EVT-2602",
    title: "Women's Volleyball Tactical Session",
    type: "Training",
    sportCategory: "Volleyball",
    status: "Ongoing",
    visibility: "Private",
    resultStatus: "Pending Results",
    venue: "Fr. Godofredo Alingal Gym",
    organizer: "Coach Sarah Lim",
    description:
      "Rotation discipline, reception patterns, and late-set communication work for the women's volleyball squad.",
    publicDescription:
      "Closed varsity volleyball tactical session for season preparation.",
    internalNotes:
      "Film breakdown follows court work. Shoulder load should be monitored for setters.",
    startDate: "2026-05-14",
    endDate: "2026-05-14",
    startTime: "15:00",
    endTime: "18:00",
    maxParticipants: 18,
    publishedAt: "",
    overallResult: "Session in progress. Staff are collecting rotation and reception notes.",
    winner: "",
    teamResult: "Second unit reception improved across pressure reps.",
    resultVisibility: "Internal Only",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-002",
        participationStatus: "Participated",
        attendanceStatus: "Present",
        resultStatus: "Pending Results",
        placement: "Rotation unit lead",
        scoreStatistics: "Serve receive efficiency 86%",
        performanceNotes: "Held the second unit together during pressure reps.",
        coachRemarks: "Composure and quick reads stood out; transition footwork next.",
        evaluatedBy: "Coach Sarah Lim",
        evaluationDate: "2026-05-14",
        metrics: [
          {
            name: "Serve receive",
            value: "86",
            unit: "%",
            notes: "Target above 80%",
          },
          {
            name: "Assist quality",
            value: "18",
            unit: "sets",
            notes: "Above session average",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2603",
    title: "University Open Football Tryouts",
    type: "Tryout",
    sportCategory: "Football",
    status: "Draft",
    visibility: "Private",
    resultStatus: "Not Started",
    venue: "Upper Football Pitch",
    organizer: "Coach Marco Alarcon",
    description:
      "Scouting-focused open tryout to identify incoming student-athletes for the next collegiate season.",
    publicDescription:
      "Prospective football student-athletes will be evaluated through technical and fitness stations once the event is published.",
    internalNotes:
      "Medical clearance booth still pending assignment. Do not publish until student affairs confirms registration protocol.",
    startDate: "2026-05-23",
    endDate: "2026-05-23",
    startTime: "06:30",
    endTime: "11:30",
    maxParticipants: 60,
    publishedAt: "",
    overallResult: "",
    winner: "",
    teamResult: "",
    resultVisibility: "Internal Only",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-003",
        participationStatus: "Assigned",
        attendanceStatus: "Pending",
        resultStatus: "Not Started",
        placement: "Support role",
        scoreStatistics: "Pending",
        performanceNotes: "Current varsity player assisting with drills.",
        coachRemarks: "Leadership presence expected at skill stations.",
        evaluatedBy: "Coach Marco Alarcon",
        evaluationDate: "2026-05-23",
        metrics: [
          {
            name: "Drill stations led",
            value: "3",
            unit: "stations",
            notes: "Support role",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2604",
    title: "Inter-Schools Swimming Invitational",
    type: "Competition",
    sportCategory: "Swimming",
    status: "Completed",
    visibility: "Public",
    resultStatus: "Published",
    venue: "Ateneo Aquatics Center",
    organizer: "Coach Isabel Torres",
    description:
      "Regional invitational meet featuring partner schools and timed race evaluations for returning swimmers.",
    publicDescription:
      "Regional invitational swimming meet with partner schools and published race outcomes.",
    internalNotes:
      "Archive official heat sheets with final summary report.",
    startDate: "2026-05-10",
    endDate: "2026-05-10",
    startTime: "09:00",
    endTime: "17:00",
    maxParticipants: 32,
    publishedAt: "2026-05-11T09:30:00",
    overallResult:
      "ADNU finished second overall with strong podium performances in freestyle and medley events.",
    winner: "Naga Regional Aquatics Club",
    teamResult: "ADNU Blue Eagles Aquatics - 2nd Overall",
    resultVisibility: "Public",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-005",
        participationStatus: "Completed",
        attendanceStatus: "Present",
        resultStatus: "Published",
        placement: "2nd Place - 100m Freestyle",
        scoreStatistics: "54.11 seconds",
        performanceNotes: "Season-best swim with strong turn efficiency.",
        coachRemarks: "Strong finish and disciplined pacing. Start reaction needs trimming.",
        evaluatedBy: "Coach Isabel Torres",
        evaluationDate: "2026-05-10",
        metrics: [
          {
            name: "100m freestyle",
            value: "54.11",
            unit: "seconds",
            notes: "Season best",
          },
          {
            name: "Reaction time",
            value: "0.72",
            unit: "seconds",
            notes: "Needs trimming",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2605",
    title: "Athlete Leadership and Wellness Seminar",
    type: "Seminar",
    sportCategory: "Other",
    status: "Cancelled",
    visibility: "Public",
    resultStatus: "Not Started",
    venue: "Athletics Conference Hall",
    organizer: "Office of Student Formation",
    description:
      "Seminar on athlete wellness, captaincy standards, and balancing academic and athletic responsibilities.",
    publicDescription:
      "Leadership and wellness seminar for university student-athletes. This event has been cancelled and will be rescheduled.",
    internalNotes:
      "Cancelled due to speaker travel disruption. Reschedule in June.",
    startDate: "2026-05-12",
    endDate: "2026-05-12",
    startTime: "13:30",
    endTime: "16:00",
    maxParticipants: 80,
    publishedAt: "",
    overallResult: "Cancelled before delivery.",
    winner: "",
    teamResult: "",
    resultVisibility: "Internal Only",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-008",
        participationStatus: "Excused",
        attendanceStatus: "Excused",
        resultStatus: "Not Started",
        placement: "N/A",
        scoreStatistics: "N/A",
        performanceNotes: "Session cancelled.",
        coachRemarks: "Rebook when new date is confirmed.",
        evaluatedBy: "Office of Student Formation",
        evaluationDate: "2026-05-12",
        metrics: [],
      },
    ],
  },
  {
    id: "EVT-2606",
    title: "Regional Athletics Qualifier",
    type: "Competition",
    sportCategory: "Athletics",
    status: "Completed",
    visibility: "Public",
    resultStatus: "Results Recorded",
    venue: "University Oval Track",
    organizer: "Coach Marcus Thorne",
    description:
      "Track and field qualifier for athletes attempting to secure regional university meet slots.",
    publicDescription:
      "Track and field qualification event with official results pending publication.",
    internalNotes:
      "Verify timing sheet before public release.",
    startDate: "2026-05-09",
    endDate: "2026-05-09",
    startTime: "07:00",
    endTime: "15:30",
    maxParticipants: 40,
    publishedAt: "",
    overallResult:
      "ADNU secured three provisional qualifying marks across sprint and field events.",
    winner: "ADNU Track and Field",
    teamResult: "3 provisional qualifiers",
    resultVisibility: "Internal Only",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-004",
        participationStatus: "Completed",
        attendanceStatus: "Present",
        resultStatus: "Results Recorded",
        placement: "1st Place - 100m",
        scoreStatistics: "11.92 seconds",
        performanceNotes: "Won heat and met regional provisional mark.",
        coachRemarks: "Excellent acceleration; maintain taper plan.",
        evaluatedBy: "Coach Marcus Thorne",
        evaluationDate: "2026-05-09",
        metrics: [
          {
            name: "100m time",
            value: "11.92",
            unit: "seconds",
            notes: "Provisional qualifier",
          },
          {
            name: "Placement",
            value: "1",
            unit: "rank",
            notes: "Heat winner",
          },
        ],
      },
    ],
  },
  {
    id: "EVT-2607",
    title: "Community Chess Exhibition",
    type: "Outreach Event",
    sportCategory: "Chess",
    status: "Scheduled",
    visibility: "Public",
    resultStatus: "Not Started",
    venue: "University Atrium",
    organizer: "Coach Emilia Bautista",
    description:
      "Public chess exhibition where varsity athletes host simultaneous boards for partner schools.",
    publicDescription:
      "A public chess exhibition featuring varsity student-athletes and invited partner schools.",
    internalNotes:
      "Keep athlete academic schedules protected. No private ratings on public collateral.",
    startDate: "2026-05-28",
    endDate: "2026-05-28",
    startTime: "10:00",
    endTime: "14:00",
    maxParticipants: 20,
    publishedAt: "",
    overallResult: "",
    winner: "",
    teamResult: "",
    resultVisibility: "Internal Only",
    assignedAthletes: [
      {
        athleteId: "ATH-2026-008",
        participationStatus: "Confirmed",
        attendanceStatus: "Pending",
        resultStatus: "Not Started",
        placement: "Exhibition board lead",
        scoreStatistics: "Pending",
        performanceNotes: "Board one showcase assignment.",
        coachRemarks: "Prepare short public-facing remarks.",
        evaluatedBy: "Coach Emilia Bautista",
        evaluationDate: "2026-05-28",
        metrics: [],
      },
    ],
  },
];

export const mockCompetitionResults = [
  {
    id: "RES-001",
    eventId: "EVT-2604",
    sport: "Swimming",
    date: "2026-05-10",
    venue: "Ateneo Aquatics Center",
    teamA: "ADNU Blue Eagles",
    teamB: "Naga Regional Aquatics",
    scoreA: 520,
    scoreB: 560,
    winner: "Naga Regional Aquatics",
    winnerStatus: "Final",
    resultSummary: "ADNU finished 2nd with strong performances in freestyle and medley events.",
  },
  {
    id: "RES-002",
    eventId: "EVT-2608",
    sport: "Basketball",
    date: "2026-05-08",
    venue: "Main Gym",
    teamA: "ADNU Blue Eagles",
    teamB: "STI Stags",
    scoreA: 100,
    scoreB: 98,
    winner: "ADNU Blue Eagles",
    winnerStatus: "Final",
    resultSummary: "ADNU secured a thrilling 2-point victory with strong defensive plays in the final quarter.",
  },
  {
    id: "RES-003",
    eventId: "EVT-2609",
    sport: "Volleyball",
    date: "2026-05-06",
    venue: "Fr. Godofredo Alingal Gym",
    teamA: "ADNU Blue Eagles Women",
    teamB: "UNC Lady Tigers",
    scoreA: 3,
    scoreB: 1,
    winner: "ADNU Blue Eagles Women",
    winnerStatus: "Final",
    resultSummary: "ADNU Women's team dominated the match with consistent set victories.",
  },
  {
    id: "RES-004",
    eventId: "EVT-2610",
    sport: "Football",
    date: "2026-05-03",
    venue: "Upper Football Pitch",
    teamA: "ADNU Football Club",
    teamB: "USI Falcon FC",
    scoreA: 2,
    scoreB: 0,
    winner: "ADNU Football Club",
    winnerStatus: "Final",
    resultSummary: "Clean sheet victory for ADNU with aggressive first-half play securing both goals.",
  },
  {
    id: "RES-005",
    eventId: "EVT-2611",
    sport: "Badminton",
    date: "2026-05-01",
    venue: "Sports Complex Court A",
    teamA: "ADNU Racquet Team",
    teamB: "NCF Badminton Club",
    scoreA: 4,
    scoreB: 2,
    winner: "ADNU Racquet Team",
    winnerStatus: "Final",
    resultSummary: "ADNU won the interclub doubles tournament with strong net play and positioning.",
  },
];

export const mockEvents = eventRecords.map((event) => {
  const enhancement = defaultEventEnhancements[event.id] ?? {};

  return {
    archived: false,
    callTime: event.startTime,
    scheduleNotes: event.internalNotes,
    publicNotes: event.publicDescription ? [event.publicDescription] : [],
    internalNoteEntries: event.internalNotes
      ? [
          {
            id: `NOTE-${event.id}-BASE`,
            title: "Staff note",
            visibility: "Internal",
            body: event.internalNotes,
            author: event.organizer,
            createdAt: `${event.startDate}T${event.startTime}:00`,
          },
        ]
      : [],
    activityLog: [
      `${event.startDate} - Event created for ${event.sportCategory}.`,
      ...(event.publishedAt ? [`${event.publishedAt.slice(0, 10)} - Results published.`] : []),
    ],
    ...event,
    ...enhancement,
  };
});
