export const currentAthleteRole = "Staff/Admin";

export const athleteStatuses = ["Cleared", "Injured", "Pending Review", "Inactive", "Archived"];
export const academicStandings = ["Dean's List", "Good", "Probation", "At Risk"];
export const yearLevels = ["Freshman Year", "Sophomore Year", "Junior Year", "Senior Year"];
export const scholarshipTypes = ["Full Scholarship", "Partial Scholarship", "Walk-on"];
export const sports = ["Basketball", "Track & Field", "Volleyball", "Football", "Swimming"];

export const mockAthletes = [
  {
    id: "#2021-08422",
    name: "Sarah Jenkins",
    sport: "Track & Field",
    department: "Department of Computer Studies",
    course: "BS Information Technology",
    event: "400m Hurdles",
    standing: "Dean's List",
    status: "Cleared",
    coach: "Marcus Thorne",
    year: "Junior Year",
    scholarship: "Full Scholarship",
    gpa: 3.85,
    imageUrl: "https://i.pravatar.cc/150?u=a042581f4e290260241",
    updatedAt: "2026-05-14",
    personal: {
      birthdate: "2003-05-18",
      age: "22 years old",
      gender: "Female",
      nationality: "Filipino",
      height: "170 cm",
      weight: "60 kg",
      bloodType: "O+",
      side: "Right lead leg",
    },
    contact: {
      phone: "+63 917 555 0188",
      email: "sarah.jenkins@adnu.edu.ph",
      address: "Unit 4, Loyola Heights, Quezon City",
      emergency: {
        name: "Martha Jenkins",
        relationship: "Mother",
        phone: "+63 917 555 0141",
      },
    },
    overview: {
      summary:
        "High-priority sprint athlete preparing for regional qualifiers with strong academic standing and stable medical clearance.",
      eligibility: "Fully eligible",
      eligibilityNote: "Cleared for all meets",
      trainingLoad: "High volume",
      trainingNote: "Tempo and hurdle phase",
      nextReview: "May 20, 2026",
      reviewOwner: "Coach and physio",
      alerts: [
        {
          title: "Achilles monitoring",
          body: "Left Achilles soreness is under observation after back-to-back hurdle sessions.",
          level: "attention",
        },
        {
          title: "Qualifier preparation",
          body: "Coaching staff is tapering volume this week to sharpen race-day execution.",
          level: "good",
        },
      ],
      recentActivity: [
        "Medical file verified for the May competition window.",
        "Hurdle rhythm block updated by Marcus Thorne.",
      ],
    },
    academics: {
      attendance: "96%",
      attendanceNote: "No missed labs this term",
      units: "21 units",
      term: "2nd Semester 2025-2026",
      eligibility: "Competition eligible",
      eligibilityNote: "No compliance holds",
      trend: [
        { label: "S1 '24", value: 68, score: "3.42" },
        { label: "S2 '24", value: 73, score: "3.56" },
        { label: "S1 '25", value: 82, score: "3.71" },
        { label: "Current", value: 94, score: "3.85", active: true },
      ],
      currentSubjects: [
        { name: "Sports Psychology", grade: "A-", schedule: "MWF 10:00 AM" },
        { name: "Statistics", grade: "A", schedule: "TTH 1:30 PM" },
        { name: "Media Writing", grade: "B+", schedule: "MWF 2:00 PM" },
      ],
      notes: [
        {
          title: "Adviser note",
          owner: "Prof. Elaine Cruz",
          body: "Sarah remains ahead on major academic requirements.",
          date: "May 13, 2026",
        },
      ],
      history: [
        { date: "May 2026", detail: "Dean's list standing confirmed for compliance review." },
        { date: "March 2026", detail: "Travel-study plan completed before regional qualifier." },
      ],
    },
    eventsParticipation: {
      items: [
        {
          id: "EVT-SAR-001",
          title: "Regional Hurdles Qualifier",
          type: "Competition",
          date: "May 9, 2026",
          venue: "University Oval Track",
          status: "Completed",
          participation: "Participated",
          attendance: "Present",
          result: "1st Place",
          coach: "Marcus Thorne",
          summary: "Posted a personal best and qualified for the national university meet.",
          metrics: ["54.2 sec", "Reaction +0.11", "PB achieved"],
        },
        {
          id: "EVT-SAR-002",
          title: "National University Athletics Meet",
          type: "Competition",
          date: "May 28, 2026",
          venue: "Metro Athletics Complex",
          status: "Upcoming",
          participation: "Confirmed",
          attendance: "Scheduled",
          result: "Pending",
          coach: "Marcus Thorne",
          summary: "Seeded among the top hurdle athletes in the region.",
          metrics: ["Seed #2", "Travel cleared", "Race heat pending"],
        },
      ],
      notes: [
        {
          title: "Competition planning",
          date: "May 13, 2026",
          description: "Reduced class travel conflict approved after schedule review.",
        },
      ],
      roles: ["Starter", "Heat leader", "Relay reserve"],
    },
    achievements: [
      {
        title: "School Record Watchlist",
        date: "2026 Outdoor Season",
        description: "Within 0.6 seconds of the current school record.",
      },
      {
        title: "Academic Merit Recognition",
        date: "1st Semester 2025-2026",
        description: "Recognized by the college dean for maintaining above 3.8 GPA.",
      },
    ],
    documents: [
      {
        id: "DOC-SAR-001",
        name: "Scholarship_Agreement.pdf",
        meta: "Signed Oct 12, 2025 | 2.4 MB",
        kind: "pdf",
        status: "Submitted",
      },
      {
        id: "DOC-SAR-002",
        name: "Medical_Clearance_2026.docx",
        meta: "Expires Jun 20, 2026 | 1.1 MB",
        kind: "doc",
        status: "Pending Review",
      },
    ],
    equipmentHistory: [
      {
        id: "GEAR-SAR-001",
        name: "Nike Air Zoom Victory",
        serial: "#TK-8912",
        issuedDate: "Nov 02, 2025",
        dueDate: "Jun 15, 2026",
        status: "In Possession",
        condition: "Good",
        icon: "shoe",
      },
      {
        id: "GEAR-SAR-002",
        name: "Polar H10 Heart Monitor",
        serial: "#SN-90221",
        issuedDate: "Apr 28, 2026",
        dueDate: "May 12, 2026",
        status: "Overdue",
        condition: "Working",
        icon: "monitor",
      },
    ],
  },
  {
    id: "#2022-09114",
    name: "Marcus Santos",
    sport: "Basketball",
    department: "Department of Business Management",
    course: "BS Business Administration",
    event: "Point Guard",
    standing: "Good",
    status: "Injured",
    coach: "David Reyes",
    year: "Sophomore Year",
    scholarship: "Partial Scholarship",
    gpa: 3.2,
    imageUrl: "https://i.pravatar.cc/150?u=a042581f4e290260242",
    updatedAt: "2026-05-13",
    personal: {
      birthdate: "2004-09-03",
      age: "21 years old",
      gender: "Male",
      nationality: "Filipino",
      height: "182 cm",
      weight: "77 kg",
      bloodType: "A+",
      side: "Right hand dominant",
    },
    contact: {
      phone: "+63 917 555 0226",
      email: "marcus.santos@adnu.edu.ph",
      address: "Magsaysay Avenue, Naga City",
      emergency: {
        name: "Roberto Santos",
        relationship: "Father",
        phone: "+63 917 555 0208",
      },
    },
    overview: {
      summary:
        "Floor general in a rehab rotation after a minor ankle sprain, with close coordination between coaching and sports medicine.",
      eligibility: "Conditionally active",
      eligibilityNote: "Awaiting return-to-play signoff",
      trainingLoad: "Modified",
      trainingNote: "Non-contact sessions only",
      nextReview: "May 18, 2026",
      reviewOwner: "Team physician",
      alerts: [
        {
          title: "Return-to-play phase",
          body: "Marcus should remain out of full-contact drills until the next movement check.",
          level: "attention",
        },
        {
          title: "Leadership role retained",
          body: "Still leading film breakdown and half-court organization during meetings.",
          level: "good",
        },
      ],
      recentActivity: [
        "Functional movement check logged by sports medicine.",
        "Coach added him to the backcourt tactical review.",
      ],
    },
    academics: {
      attendance: "93%",
      attendanceNote: "Excused rehab travel only",
      units: "19 units",
      term: "2nd Semester 2025-2026",
      eligibility: "Eligible with monitoring",
      eligibilityNote: "Maintain attendance above 90%",
      trend: [
        { label: "S1 '24", value: 58, score: "2.94" },
        { label: "S2 '24", value: 63, score: "3.05" },
        { label: "S1 '25", value: 72, score: "3.16" },
        { label: "Current", value: 80, score: "3.20", active: true },
      ],
      currentSubjects: [
        { name: "Marketing", grade: "B+", schedule: "MWF 9:00 AM" },
        { name: "Human Kinetics", grade: "A-", schedule: "TTH 10:30 AM" },
        { name: "Business Ethics", grade: "B", schedule: "MWF 1:00 PM" },
      ],
      notes: [
        {
          title: "Faculty note",
          owner: "Prof. Miguel De Leon",
          body: "Marcus remains engaged in class discussion and benefits from early submission pacing.",
          date: "May 10, 2026",
        },
      ],
      history: [
        { date: "May 2026", detail: "Eligibility kept active with attendance monitoring." },
        { date: "January 2026", detail: "Rehab schedule approved for class conflict exceptions." },
      ],
    },
    eventsParticipation: {
      items: [
        {
          id: "EVT-MAR-001",
          title: "Backcourt Tactical Film Review",
          type: "Team Meeting",
          date: "May 11, 2026",
          venue: "Basketball War Room",
          status: "Completed",
          participation: "Participated",
          attendance: "Present",
          result: "Led review",
          coach: "David Reyes",
          summary: "Led point-guard film breakdown while on restricted court participation.",
          metrics: ["3 scouting clips", "2 player briefings", "Full attendance"],
        },
        {
          id: "EVT-MAR-002",
          title: "Pre-Season Basketball Combine",
          type: "Fitness Test",
          date: "May 18, 2026",
          venue: "Main Gym Performance Lab",
          status: "Upcoming",
          participation: "Assigned",
          attendance: "Scheduled",
          result: "Pending",
          coach: "David Reyes",
          summary: "Selected performance tests pending final ankle clearance.",
          metrics: ["Clearance pending", "Jump tests limited", "Medical review"],
        },
      ],
      notes: [
        {
          title: "Rehab participation rule",
          date: "May 12, 2026",
          description: "May attend tactical sessions but must stay on controlled minutes.",
        },
      ],
      roles: ["Point guard", "Film lead", "Backcourt captain"],
    },
    achievements: [
      {
        title: "Assist-to-turnover leader",
        date: "2025 University League",
        description: "Finished with the best assist-to-turnover ratio on the team.",
      },
    ],
    documents: [
      {
        id: "DOC-MAR-001",
        name: "Rehab_Clearance_Update.pdf",
        meta: "Uploaded May 11, 2026 | 980 KB",
        kind: "pdf",
        status: "Submitted",
      },
    ],
    equipmentHistory: [
      {
        id: "GEAR-MAR-001",
        name: "Ankle Brace Set",
        serial: "#BB-7719",
        issuedDate: "Jan 24, 2026",
        dueDate: "Jun 01, 2026",
        status: "In Possession",
        condition: "Good",
        icon: "shoe",
      },
    ],
  },
  {
    id: "#2020-04192",
    name: "Elena Rodriguez",
    sport: "Volleyball",
    department: "Department of Communication",
    course: "BA Communication",
    event: "Libero",
    standing: "Probation",
    status: "Pending Review",
    coach: "Sarah Lim",
    year: "Senior Year",
    scholarship: "Walk-on",
    gpa: 2.1,
    imageUrl: "https://i.pravatar.cc/150?u=a042581f4e290260243",
    updatedAt: "2026-05-12",
    personal: {
      birthdate: "2002-12-12",
      age: "23 years old",
      gender: "Female",
      nationality: "Filipino",
      height: "165 cm",
      weight: "58 kg",
      bloodType: "B+",
      side: "Right hand dominant",
    },
    contact: {
      phone: "+63 917 555 0314",
      email: "elena.rodriguez@adnu.edu.ph",
      address: "Pacol Road, Naga City",
      emergency: {
        name: "Lourdes Rodriguez",
        relationship: "Aunt",
        phone: "+63 917 555 0301",
      },
    },
    overview: {
      summary:
        "Senior libero balancing final-year eligibility concerns with academic recovery and document renewal requirements.",
      eligibility: "At risk",
      eligibilityNote: "Pending compliance review",
      trainingLoad: "Controlled",
      trainingNote: "Practice volume trimmed during finals",
      nextReview: "May 16, 2026",
      reviewOwner: "Compliance office",
      alerts: [
        {
          title: "Academic intervention active",
          body: "Mandatory tutoring and weekly faculty check-ins remain active until grades stabilize.",
          level: "attention",
        },
        {
          title: "Roster value remains strong",
          body: "Defensive communication and serve-receive coverage remain important to the current unit.",
          level: "good",
        },
      ],
      recentActivity: [
        "Eligibility paperwork flagged for follow-up.",
        "Academic services added writing support sessions.",
      ],
    },
    academics: {
      attendance: "88%",
      attendanceNote: "Needs immediate improvement",
      units: "18 units",
      term: "2nd Semester 2025-2026",
      eligibility: "Probationary",
      eligibilityNote: "Final review after grading period",
      trend: [
        { label: "S1 '24", value: 66, score: "3.12" },
        { label: "S2 '24", value: 60, score: "2.90" },
        { label: "S1 '25", value: 54, score: "2.54" },
        { label: "Current", value: 48, score: "2.10", active: true },
      ],
      currentSubjects: [
        { name: "Research Methods", grade: "C+", schedule: "MWF 8:00 AM" },
        { name: "Organizational Comm", grade: "B-", schedule: "TTH 11:00 AM" },
        { name: "Internship Prep", grade: "C", schedule: "MWF 3:00 PM" },
      ],
      notes: [
        {
          title: "Academic probation note",
          owner: "Registrar Compliance",
          body: "Elena must complete missing submissions and sustain weekly attendance above minimum threshold.",
          date: "May 8, 2026",
        },
      ],
      history: [
        { date: "May 2026", detail: "Probation plan retained until grades post." },
        { date: "April 2026", detail: "Tutoring cadence increased to twice weekly." },
      ],
    },
    eventsParticipation: {
      items: [
        {
          id: "EVT-ELE-001",
          title: "Women's Volleyball Tactical Session",
          type: "Training",
          date: "May 14, 2026",
          venue: "Fr. Godofredo Alingal Gym",
          status: "Ongoing",
          participation: "Confirmed",
          attendance: "Present",
          result: "2nd unit libero",
          coach: "Sarah Lim",
          summary: "Active in reception and communication drills with reduced workload.",
          metrics: ["86% receive", "Low jump load", "Full walkthrough"],
        },
        {
          id: "EVT-ELE-002",
          title: "Conference Defensive Tune-Up",
          type: "Competition",
          date: "May 21, 2026",
          venue: "City Sports Center",
          status: "Upcoming",
          participation: "Assigned",
          attendance: "Scheduled",
          result: "Pending",
          coach: "Sarah Lim",
          summary: "Projected for a reduced defensive role if compliance documents are completed.",
          metrics: ["Roster pending", "Doc review", "Travel hold"],
        },
      ],
      notes: [
        {
          title: "Attendance concern",
          date: "May 8, 2026",
          description: "Missed one optional walkthrough during exam pressure week.",
        },
      ],
      roles: ["Libero", "Serve receive anchor", "Defensive specialist"],
    },
    achievements: [
      {
        title: "Best Receiver of the Match",
        date: "Conference Round 2, 2025",
        description: "Recorded the cleanest first-ball platform grade on the team.",
      },
    ],
    documents: [
      {
        id: "DOC-ELE-001",
        name: "Eligibility_Review_Request.pdf",
        meta: "Submitted for review | 730 KB",
        kind: "pdf",
        status: "Pending Review",
      },
      {
        id: "DOC-ELE-002",
        name: "Medical_Renewal_Form.docx",
        meta: "Pending physician signature | 1.0 MB",
        kind: "doc",
        status: "Missing",
      },
    ],
    equipmentHistory: [
      {
        id: "GEAR-ELE-001",
        name: "Knee Pad Set",
        serial: "#VB-2341",
        issuedDate: "Aug 10, 2025",
        dueDate: "Jun 10, 2026",
        status: "In Possession",
        condition: "Good",
        icon: "shoe",
      },
      {
        id: "GEAR-ELE-002",
        name: "Recovery Compression Boots",
        serial: "#VB-8810",
        issuedDate: "Apr 22, 2026",
        dueDate: "May 08, 2026",
        status: "Overdue",
        condition: "Needs review",
        icon: "monitor",
      },
    ],
  },
];

export function createAthleteFromForm(values) {
  const now = new Date().toISOString().slice(0, 10);

  return {
    id: values.id.trim(),
    name: values.name.trim(),
    sport: values.sport,
    department: values.department.trim(),
    course: values.course.trim(),
    event: values.event.trim(),
    standing: values.standing,
    status: values.status,
    coach: values.coach.trim(),
    year: values.year,
    scholarship: values.scholarship,
    gpa: Number(values.gpa || 0),
    imageUrl: `https://i.pravatar.cc/150?u=${encodeURIComponent(values.id || values.name)}`,
    updatedAt: now,
    personal: {
      birthdate: values.birthdate || "",
      age: values.age || "Pending",
      gender: values.gender || "Pending",
      nationality: values.nationality || "Filipino",
      height: values.height || "Pending",
      weight: values.weight || "Pending",
      bloodType: values.bloodType || "Pending",
      side: values.side || "Pending",
    },
    contact: {
      phone: values.phone.trim(),
      email: values.email.trim(),
      address: values.address.trim(),
      emergency: {
        name: values.emergencyName.trim(),
        relationship: values.emergencyRelationship.trim(),
        phone: values.emergencyPhone.trim(),
      },
    },
    overview: {
      summary:
        values.summary ||
        "New athlete profile created locally. Staff can complete profile details before backend persistence is connected.",
      eligibility: values.status === "Cleared" ? "Fully eligible" : "Needs review",
      eligibilityNote: "Local frontend record",
      trainingLoad: "Pending",
      trainingNote: "Awaiting coach plan",
      nextReview: "Not scheduled",
      reviewOwner: "Athlete Services",
      alerts: [],
      recentActivity: ["Athlete profile created locally."],
    },
    academics: {
      attendance: values.attendance || "Pending",
      attendanceNote: "Awaiting academic sync",
      units: values.units || "Pending",
      term: "2nd Semester 2025-2026",
      eligibility: values.academicEligibility || "Pending review",
      eligibilityNote: "Local frontend record",
      trend: [{ label: "Current", value: 50, score: values.gpa || "0.00", active: true }],
      currentSubjects: [],
      notes: [],
      history: [],
    },
    eventsParticipation: {
      items: [],
      notes: [],
      roles: [values.event.trim()].filter(Boolean),
    },
    achievements: [],
    documents: [],
    equipmentHistory: [],
  };
}
