import {
  emptyFacilityForm,
  emptyReservationForm,
  formatDateTime,
} from "./facilityTypes";

export const currentFacilityRole = "Staff/Admin";

export const documentTemplates = [
  {
    id: "REQ-INTERNAL-FORM",
    name: "Reservation request form",
    required: true,
    appliesTo: ["Internal", "Student Organization", "Staff", "Athlete/Coach"],
  },
  {
    id: "REQ-ENDORSEMENT",
    name: "Adviser or department endorsement",
    required: false,
    appliesTo: ["Student Organization", "Athlete/Coach"],
  },
  {
    id: "REQ-PROPOSAL",
    name: "Event or activity proposal",
    required: true,
    appliesTo: ["Student Organization", "External/Outsider", "Partner Organization"],
  },
  {
    id: "REQ-LETTER",
    name: "Formal request letter",
    required: true,
    appliesTo: ["External/Outsider", "Partner Organization"],
  },
  {
    id: "REQ-ID",
    name: "Valid ID or representative ID",
    required: true,
    appliesTo: ["External/Outsider", "Partner Organization"],
  },
  {
    id: "REQ-WAIVER",
    name: "Waiver or liability agreement",
    required: true,
    appliesTo: ["External/Outsider", "Partner Organization", "Student Organization"],
  },
  {
    id: "REQ-PAYMENT",
    name: "Proof of payment or payment reference",
    required: false,
    appliesTo: ["External/Outsider", "Partner Organization"],
  },
  {
    id: "REQ-USE-AGREEMENT",
    name: "Signed facility use agreement",
    required: true,
    appliesTo: ["External/Outsider", "Partner Organization"],
  },
];

export const mockFacilities = [
  {
    id: "FAC-001",
    name: "Main Gymnasium",
    type: "Gymnasium",
    location: "Fr. Godofredo Alingal Sports Complex",
    capacity: 1200,
    status: "Available",
    sports: ["Basketball", "Volleyball", "Badminton", "General Athletics"],
    operatingHours: "Mon-Sat, 6:00 AM - 9:00 PM",
    contactPerson: "Ms. Celina Vargas",
    managingOffice: "Athletics Facilities Office",
    description:
      "Primary indoor competition venue for varsity practices, tournaments, assemblies, and approved university events.",
    rulesSummary:
      "Court shoes required. Food and drinks are restricted to lobby areas. Setup changes require facilities approval.",
    policies: [
      "Reservation requests should be submitted at least five working days before the activity.",
      "Approved users must follow posted court safety and equipment handling rules.",
      "External events may require security, custodial, and payment clearance.",
    ],
    allowedActivities: ["Varsity practice", "Intramurals", "Tournaments", "PE classes", "Approved assemblies"],
    prohibitedActivities: ["Open flames", "Unapproved commercial selling", "Permanent floor markings"],
    requiredDocuments: documentTemplates,
    maintenanceRecords: [
      {
        id: "BLK-001",
        facilityId: "FAC-001",
        title: "Floor recoating inspection",
        reason: "Quarterly court floor inspection and spot repair.",
        startDate: "2026-05-18",
        endDate: "2026-05-18",
        startTime: "08:00",
        endTime: "12:00",
        status: "Scheduled",
        createdBy: "Facilities Supervisor",
        notes: "Half-day blockout for varnish inspection.",
      },
    ],
    notes: [
      {
        id: "NOTE-001",
        title: "Sound system handoff",
        visibility: "Internal",
        author: "Athletics Staff",
        createdAt: "2026-05-01",
        body: "Coordinate microphone and scoreboard controls with the events team for large competitions.",
      },
      {
        id: "NOTE-002",
        title: "Public reminder",
        visibility: "Public",
        author: "Facilities Office",
        createdAt: "2026-05-02",
        body: "Users must wear non-marking shoes inside the main court.",
      },
    ],
    updatedAt: "2026-05-08",
    archived: false,
  },
  {
    id: "FAC-002",
    name: "University Track Oval",
    type: "Track",
    location: "North Athletics Field",
    capacity: 600,
    status: "Limited Use",
    sports: ["Track and Field", "Football", "General Athletics"],
    operatingHours: "Mon-Sun, 5:00 AM - 8:00 PM",
    contactPerson: "Coach Marco Rivera",
    managingOffice: "Track and Field Program",
    description: "Eight-lane track with central field area for training, conditioning, and approved outdoor events.",
    rulesSummary: "Spike shoes limited to marked lanes. Field access requires coach or staff supervision.",
    policies: [
      "Lane assignments may be changed during varsity training windows.",
      "Weather advisories may close the oval without prior notice.",
    ],
    allowedActivities: ["Track training", "Conditioning", "Tryouts", "Outdoor PE classes"],
    prohibitedActivities: ["Vehicle access", "Glass containers", "Unauthorized overnight setup"],
    requiredDocuments: documentTemplates,
    maintenanceRecords: [],
    notes: [],
    updatedAt: "2026-05-06",
    archived: false,
  },
  {
    id: "FAC-003",
    name: "Aquatics Center",
    type: "Pool",
    location: "West Campus Aquatics Wing",
    capacity: 180,
    status: "Under Maintenance",
    sports: ["Swimming", "General Athletics"],
    operatingHours: "Tue-Sat, 7:00 AM - 7:00 PM",
    contactPerson: "Mr. Paolo Mendoza",
    managingOffice: "Aquatics Office",
    description: "Training and competition pool used for varsity swimming, lifesaving instruction, and aquatic fitness.",
    rulesSummary: "Certified lifeguard presence is required. Users must follow pool deck and sanitation rules.",
    policies: [
      "Pool use is suspended during chemical balancing and safety inspections.",
      "External pool use requires signed waivers and approved supervision plan.",
    ],
    allowedActivities: ["Swim practice", "Aquatic conditioning", "Water safety training"],
    prohibitedActivities: ["Diving without clearance", "Private lessons without approval", "Food on pool deck"],
    requiredDocuments: documentTemplates,
    maintenanceRecords: [
      {
        id: "BLK-002",
        facilityId: "FAC-003",
        title: "Pump room repair",
        reason: "Filter pump replacement and water quality testing.",
        startDate: "2026-05-14",
        endDate: "2026-05-20",
        startTime: "06:00",
        endTime: "18:00",
        status: "Ongoing",
        createdBy: "Maintenance Team",
        notes: "Pool unavailable until water quality clearance is posted.",
      },
    ],
    notes: [
      {
        id: "NOTE-003",
        title: "Lifeguard coverage",
        visibility: "Internal",
        author: "Aquatics Office",
        createdAt: "2026-05-03",
        body: "Confirm lifeguard availability before approving weekend external requests.",
      },
    ],
    updatedAt: "2026-05-14",
    archived: false,
  },
  {
    id: "FAC-004",
    name: "Strength and Conditioning Room",
    type: "Training Room",
    location: "Gymnasium Annex, Ground Floor",
    capacity: 45,
    status: "Available",
    sports: ["Strength and Conditioning", "Basketball", "Volleyball", "Football"],
    operatingHours: "Mon-Fri, 6:00 AM - 8:00 PM",
    contactPerson: "Coach Andrea Lim",
    managingOffice: "Performance Office",
    description: "Weight training and conditioning area for varsity teams, supervised sessions, and injury prevention work.",
    rulesSummary: "Coach supervision required for team sessions. Equipment must be returned and sanitized after use.",
    policies: ["Priority access is reserved for scheduled varsity blocks.", "Outside users are not allowed without staff escort."],
    allowedActivities: ["Team lifting", "Conditioning", "Rehab support", "Performance testing"],
    prohibitedActivities: ["Unsupervised external rentals", "Dropping weights outside platform areas"],
    requiredDocuments: documentTemplates,
    maintenanceRecords: [],
    notes: [],
    updatedAt: "2026-05-09",
    archived: false,
  },
  {
    id: "FAC-005",
    name: "Multipurpose Activity Hall",
    type: "Multipurpose Hall",
    location: "Student Wellness Center",
    capacity: 320,
    status: "Reserved",
    sports: ["General Athletics", "Badminton", "Tennis"],
    operatingHours: "Mon-Sat, 8:00 AM - 8:00 PM",
    contactPerson: "Ms. Hanna Cruz",
    managingOffice: "Athletics Facilities Office",
    description: "Flexible indoor hall for clinics, seminars, low-impact activities, team meetings, and department events.",
    rulesSummary: "Furniture layout must be returned after use. Amplified sound requires prior approval.",
    policies: ["Setups with chairs, mats, or AV equipment should be noted in the reservation request."],
    allowedActivities: ["Clinics", "Meetings", "Wellness sessions", "Low-impact training"],
    prohibitedActivities: ["High-impact ball drills", "Wet activities", "Unapproved stage setup"],
    requiredDocuments: documentTemplates,
    maintenanceRecords: [],
    notes: [],
    updatedAt: "2026-05-11",
    archived: false,
  },
];

export const mockReservations = [
  {
    id: "RSV-001",
    facilityId: "FAC-001",
    facilityName: "Main Gymnasium",
    requesterName: "Coach Miguel Santos",
    requesterType: "Athlete/Coach",
    organization: "Men's Basketball Team",
    email: "miguel.santos@adnu.edu.ph",
    contactNumber: "+63 917 555 0101",
    reservationDate: "2026-05-16",
    startTime: "15:00",
    endTime: "17:00",
    participantCount: 24,
    activityName: "Varsity Basketball Practice",
    description: "Closed team practice for defensive rotations and scrimmage work.",
    useType: "Internal",
    equipmentNeeds: "Scoreboard, 12 balls, hydration station",
    notes: "Security not required.",
    status: "Approved",
    documentStatus: "Approved",
    reviewer: "Athletics Director",
    reviewNote: "Approved within varsity training block.",
    staffNote: "Coordinate with volleyball program for court handoff.",
    documents: [
      makeDocument("DOC-001", "Reservation request form", "Approved", "basketball-request.pdf", true),
      makeDocument("DOC-002", "Adviser or department endorsement", "Approved", "coach-endorsement.pdf", false),
    ],
    activityLog: [
      "May 10, 2026 - Request submitted.",
      "May 11, 2026 - Documents reviewed.",
      "May 11, 2026 - Request approved by Athletics Director.",
    ],
    createdAt: "2026-05-10",
    updatedAt: "2026-05-11",
  },
  {
    id: "RSV-002",
    facilityId: "FAC-005",
    facilityName: "Multipurpose Activity Hall",
    requesterName: "Ateneo Wellness Club",
    requesterType: "Student Organization",
    organization: "Ateneo Wellness Club",
    email: "wellness.club@adnu.edu.ph",
    contactNumber: "+63 917 555 0202",
    reservationDate: "2026-05-15",
    startTime: "09:00",
    endTime: "12:00",
    participantCount: 80,
    activityName: "Student Wellness Clinic",
    description: "Campus wellness seminar and movement clinic for students.",
    useType: "Internal",
    equipmentNeeds: "80 chairs, wireless microphone, projector",
    notes: "Adviser will be present.",
    status: "Approved",
    documentStatus: "Approved",
    reviewer: "Facilities Coordinator",
    reviewNote: "Approved with AV support.",
    staffNote: "",
    documents: [
      makeDocument("DOC-003", "Reservation request form", "Approved", "wellness-request.pdf", true),
      makeDocument("DOC-004", "Event or activity proposal", "Approved", "wellness-proposal.pdf", true),
      makeDocument("DOC-005", "Waiver or liability agreement", "Approved", "wellness-waiver.pdf", true),
    ],
    activityLog: ["May 9, 2026 - Request submitted.", "May 10, 2026 - Request approved."],
    createdAt: "2026-05-09",
    updatedAt: "2026-05-10",
  },
  {
    id: "RSV-003",
    facilityId: "FAC-002",
    facilityName: "University Track Oval",
    requesterName: "Naga Runners Association",
    requesterType: "External/Outsider",
    organization: "Naga Runners Association",
    email: "events@nagarunners.ph",
    contactNumber: "+63 998 555 0303",
    reservationDate: "2026-05-24",
    startTime: "06:00",
    endTime: "10:00",
    participantCount: 150,
    activityName: "Community Track Clinic",
    description: "Running clinic for youth athletes with ADNU alumni volunteers.",
    useType: "External",
    equipmentNeeds: "Lane markers, first aid table, security coordination",
    notes: "Will submit insurance endorsement after approval.",
    status: "Pending Review",
    documentStatus: "Pending Review",
    reviewer: "",
    reviewNote: "",
    staffNote: "",
    documents: [
      makeDocument("DOC-006", "Formal request letter", "Submitted", "nra-request-letter.pdf", true),
      makeDocument("DOC-007", "Valid ID or representative ID", "Submitted", "representative-id.pdf", true),
      makeDocument("DOC-008", "Event or activity proposal", "Submitted", "track-clinic-proposal.pdf", true),
      makeDocument("DOC-009", "Waiver or liability agreement", "Missing", "", true),
      makeDocument("DOC-010", "Proof of payment or payment reference", "Missing", "", false),
    ],
    activityLog: ["May 12, 2026 - Request submitted.", "May 13, 2026 - Initial document check started."],
    createdAt: "2026-05-12",
    updatedAt: "2026-05-13",
  },
  {
    id: "RSV-004",
    facilityId: "FAC-004",
    facilityName: "Strength and Conditioning Room",
    requesterName: "Coach Andrea Lim",
    requesterType: "Staff",
    organization: "Performance Office",
    email: "andrea.lim@adnu.edu.ph",
    contactNumber: "+63 917 555 0404",
    reservationDate: "2026-05-22",
    startTime: "13:00",
    endTime: "15:00",
    participantCount: 18,
    activityName: "Return-to-Play Testing",
    description: "Performance testing for cleared athletes returning from injury.",
    useType: "Internal",
    equipmentNeeds: "Force plates, testing laptop",
    notes: "",
    status: "Pending Review",
    documentStatus: "Submitted",
    reviewer: "",
    reviewNote: "",
    staffNote: "",
    documents: [makeDocument("DOC-011", "Reservation request form", "Submitted", "rtp-request.pdf", true)],
    activityLog: ["May 14, 2026 - Request submitted."],
    createdAt: "2026-05-14",
    updatedAt: "2026-05-14",
  },
  {
    id: "RSV-005",
    facilityId: "FAC-001",
    facilityName: "Main Gymnasium",
    requesterName: "Junior Volleyball Program",
    requesterType: "Partner Organization",
    organization: "Junior Volleyball Program",
    email: "admin@jvp.example",
    contactNumber: "+63 917 555 0505",
    reservationDate: "2026-05-02",
    startTime: "08:00",
    endTime: "11:00",
    participantCount: 60,
    activityName: "Youth Volleyball Clinic",
    description: "Partner organization clinic for junior players.",
    useType: "External",
    equipmentNeeds: "Volleyball nets and score table",
    notes: "",
    status: "Completed",
    documentStatus: "Approved",
    reviewer: "Facilities Coordinator",
    reviewNote: "Completed without incident.",
    staffNote: "",
    documents: [
      makeDocument("DOC-012", "Formal request letter", "Approved", "jvp-letter.pdf", true),
      makeDocument("DOC-013", "Signed facility use agreement", "Approved", "jvp-use-agreement.pdf", true),
    ],
    activityLog: [
      "Apr 24, 2026 - Request submitted.",
      "Apr 26, 2026 - Request approved.",
      "May 2, 2026 - Reservation marked completed.",
    ],
    createdAt: "2026-04-24",
    updatedAt: "2026-05-02",
  },
  {
    id: "RSV-006",
    facilityId: "FAC-003",
    facilityName: "Aquatics Center",
    requesterName: "Blue Marlins Club",
    requesterType: "External/Outsider",
    organization: "Blue Marlins Club",
    email: "bookings@bluemarlins.example",
    contactNumber: "+63 917 555 0606",
    reservationDate: "2026-05-17",
    startTime: "08:00",
    endTime: "10:00",
    participantCount: 30,
    activityName: "Weekend Swim Camp",
    description: "External swim camp request during maintenance period.",
    useType: "External",
    equipmentNeeds: "Lane ropes",
    notes: "Requested before maintenance notice was posted.",
    status: "Rejected",
    documentStatus: "Rejected",
    reviewer: "Aquatics Office",
    reviewNote: "Rejected because pump room repair closes the pool through May 20.",
    staffNote: "",
    documents: [makeDocument("DOC-014", "Formal request letter", "Rejected", "swim-camp-letter.pdf", true)],
    activityLog: ["May 8, 2026 - Request submitted.", "May 9, 2026 - Request rejected due to maintenance blockout."],
    createdAt: "2026-05-08",
    updatedAt: "2026-05-09",
  },
];

export function makeDocument(id, name, status = "Missing", fileName = "", required = true) {
  return {
    id,
    name,
    required,
    status,
    fileName,
    uploadedAt: fileName ? "2026-05-12" : "",
    reviewedBy: status === "Approved" || status === "Rejected" ? "Athletics Staff" : "",
    note: status === "Rejected" ? "Please upload the corrected version." : "",
  };
}

export function facilityToForm(facility) {
  if (!facility) return { ...emptyFacilityForm };
  return {
    name: facility.name,
    type: facility.type,
    location: facility.location,
    capacity: String(facility.capacity),
    status: facility.status,
    sportsText: facility.sports.join(", "),
    operatingHours: facility.operatingHours,
    contactPerson: facility.contactPerson,
    managingOffice: facility.managingOffice,
    description: facility.description,
    rulesSummary: facility.rulesSummary,
  };
}

export function mergeFacilityForm(facility, values) {
  return {
    ...facility,
    name: values.name.trim(),
    type: values.type,
    location: values.location.trim(),
    capacity: Number(values.capacity),
    status: values.status,
    sports: values.sportsText
      .split(",")
      .map((sport) => sport.trim())
      .filter(Boolean),
    operatingHours: values.operatingHours.trim(),
    contactPerson: values.contactPerson.trim(),
    managingOffice: values.managingOffice.trim(),
    description: values.description.trim(),
    rulesSummary: values.rulesSummary.trim(),
    updatedAt: todayIso(),
  };
}

export function createFacilityFromForm(values) {
  return mergeFacilityForm(
    {
      id: `FAC-${String(Date.now()).slice(-3)}`,
      name: "",
      type: "Gymnasium",
      location: "",
      capacity: 0,
      status: "Available",
      sports: [],
      operatingHours: "",
      contactPerson: "",
      managingOffice: "Athletics Department",
      description: "",
      rulesSummary: "",
      policies: ["Reservation approval is required before use."],
      allowedActivities: ["Approved athletics activities"],
      prohibitedActivities: ["Unauthorized activities"],
      requiredDocuments: documentTemplates,
      maintenanceRecords: [],
      notes: [],
      updatedAt: todayIso(),
      archived: false,
    },
    values,
  );
}

export function reservationToForm(reservation) {
  if (!reservation) return { ...emptyReservationForm };
  return {
    requesterName: reservation.requesterName,
    requesterType: reservation.requesterType,
    organization: reservation.organization,
    email: reservation.email,
    contactNumber: reservation.contactNumber,
    facilityId: reservation.facilityId,
    reservationDate: reservation.reservationDate,
    startTime: reservation.startTime,
    endTime: reservation.endTime,
    participantCount: String(reservation.participantCount),
    activityName: reservation.activityName,
    description: reservation.description,
    useType: reservation.useType,
    equipmentNeeds: reservation.equipmentNeeds,
    notes: reservation.notes,
    documentsAcknowledged: true,
  };
}

export function createReservationFromForm(values, facilities) {
  const facility = facilities.find((candidate) => candidate.id === values.facilityId);
  const templates = getApplicableDocuments(facility, values.requesterType);
  const id = `RSV-${String(Date.now()).slice(-6)}`;

  return {
    id,
    facilityId: values.facilityId,
    facilityName: facility?.name ?? "Selected Facility",
    requesterName: values.requesterName.trim(),
    requesterType: values.requesterType,
    organization: values.organization.trim(),
    email: values.email.trim(),
    contactNumber: values.contactNumber.trim(),
    reservationDate: values.reservationDate,
    startTime: values.startTime,
    endTime: values.endTime,
    participantCount: Number(values.participantCount),
    activityName: values.activityName.trim(),
    description: values.description.trim(),
    useType: values.useType,
    equipmentNeeds: values.equipmentNeeds.trim(),
    notes: values.notes.trim(),
    status: "Pending Review",
    documentStatus: templates.some((doc) => doc.required) ? "Missing" : "Submitted",
    reviewer: "",
    reviewNote: "",
    staffNote: "",
    documents: templates.map((template, index) =>
      makeDocument(`DOC-${String(Date.now()).slice(-4)}-${index + 1}`, template.name, "Missing", "", template.required),
    ),
    activityLog: [`${new Date().toLocaleDateString()} - Request submitted for ${formatDateTime(values.reservationDate, values.startTime, values.endTime)}.`],
    createdAt: todayIso(),
    updatedAt: todayIso(),
  };
}

export function getApplicableDocuments(facility, requesterType) {
  const templates = facility?.requiredDocuments ?? documentTemplates;
  return templates.filter((document) => document.appliesTo?.includes(requesterType));
}

export function todayIso() {
  return new Date().toISOString().slice(0, 10);
}
