import { emptyInventoryForm, todayIso } from "./inventoryTypes";

export const inventoryPeople = [
  {
    id: "#2021-08422",
    name: "Sarah Jenkins",
    type: "Athlete",
    sport: "Track & Field",
    team: "Blue Eagles Track",
    status: "Cleared",
  },
  {
    id: "#2022-09114",
    name: "Marcus Santos",
    type: "Athlete",
    sport: "Basketball",
    team: "Blue Eagles Men",
    status: "Injured",
  },
  {
    id: "#2020-04192",
    name: "Elena Rodriguez",
    type: "Athlete",
    sport: "Volleyball",
    team: "Blue Eagles Women",
    status: "Pending Review",
  },
  {
    id: "COACH-001",
    name: "David Reyes",
    type: "Coach",
    sport: "Basketball",
    team: "Blue Eagles Men",
    status: "Active",
  },
  {
    id: "COACH-002",
    name: "Sarah Lim",
    type: "Coach",
    sport: "Volleyball",
    team: "Blue Eagles Women",
    status: "Active",
  },
  {
    id: "STAFF-ATH-001",
    name: "Nina Mercado",
    type: "Staff",
    sport: "All Athletics",
    team: "Equipment Office",
    status: "Active",
  },
];

export const mockInventoryItems = [
  {
    id: "INV-VB-042",
    sku: "ADNU-VB-042",
    name: "Mikasa V200W Pro Volleyballs",
    category: "Equipment",
    sport: "Volleyball",
    totalQuantity: 24,
    availableQuantity: 18,
    condition: "Excellent",
    status: "Partially Assigned",
    location: "Fr. Godofredo Alingal Gym",
    brand: "Mikasa",
    model: "V200W Pro",
    size: "Official size 5",
    description: "Competition-grade volleyballs used for varsity practices and official match preparation.",
    imageUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Varsity Sports Supply",
      date: "2026-02-12",
      unitCost: 78,
      warranty: "1 year manufacturer warranty",
    },
    assignments: [
      {
        id: "ASN-VB-001",
        assigneeId: "COACH-002",
        assigneeName: "Sarah Lim",
        assigneeType: "Coach",
        sport: "Volleyball",
        quantity: 6,
        assignedDate: "2026-05-08",
        dueDate: "2026-05-22",
        returnDate: "",
        status: "Active",
        conditionOut: "Excellent",
        conditionIn: "",
        notes: "Match preparation set for setter drills.",
      },
    ],
    maintenanceRecords: [
      {
        id: "MNT-VB-001",
        status: "Good",
        dateReported: "2026-04-28",
        issue: "Routine pressure inspection",
        resolution: "All active balls passed pressure check.",
        cost: 0,
        nextInspectionDate: "2026-06-01",
      },
    ],
    stockMovements: [
      { id: "STK-VB-001", date: "2026-02-12", type: "Stock received", quantity: 24, balance: 24, note: "Initial purchase" },
      { id: "STK-VB-002", date: "2026-05-08", type: "Assigned", quantity: -6, balance: 18, note: "Issued to Sarah Lim" },
    ],
    notes: [
      {
        id: "NOTE-VB-001",
        title: "Competition set",
        type: "Usage",
        body: "Keep six balls reserved for match-day warmups.",
        author: "Athletics Staff",
        createdAt: "2026-05-09",
      },
    ],
    history: [
      "Feb 12, 2026 - Item created with 24 total units.",
      "May 8, 2026 - 6 units assigned to Sarah Lim.",
      "May 9, 2026 - Usage note added.",
    ],
    updatedAt: "2026-05-14",
    archived: false,
  },
  {
    id: "INV-TM-011",
    sku: "ADNU-TM-011",
    name: "Commercial Treadmill X8",
    category: "Training Gear",
    sport: "All Athletics",
    totalQuantity: 2,
    availableQuantity: 1,
    condition: "Needs Inspection",
    status: "Under Maintenance",
    location: "Main Equipment Room",
    brand: "NordicTrack",
    model: "Commercial X8",
    size: "220V indoor unit",
    description: "High-load cardio treadmill used for conditioning blocks and return-to-play sessions.",
    imageUrl: "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Performance Lab Systems",
      date: "2025-09-10",
      unitCost: 2800,
      warranty: "Service contract through Sep 2027",
    },
    assignments: [
      {
        id: "ASN-TM-001",
        assigneeId: "STAFF-ATH-001",
        assigneeName: "Nina Mercado",
        assigneeType: "Staff",
        sport: "All Athletics",
        quantity: 1,
        assignedDate: "2026-05-01",
        dueDate: "2026-05-30",
        returnDate: "",
        status: "Active",
        conditionOut: "Good",
        conditionIn: "",
        notes: "Reserved for sports medicine rehab block.",
      },
    ],
    maintenanceRecords: [
      {
        id: "MNT-TM-001",
        status: "Under Maintenance",
        dateReported: "2026-05-13",
        issue: "Belt tracking drift and intermittent console reset.",
        resolution: "Technician visit scheduled; do not issue for sprint intervals.",
        cost: 120,
        nextInspectionDate: "2026-05-17",
      },
    ],
    stockMovements: [
      { id: "STK-TM-001", date: "2025-09-10", type: "Stock received", quantity: 2, balance: 2, note: "Initial purchase" },
      { id: "STK-TM-002", date: "2026-05-01", type: "Assigned", quantity: -1, balance: 1, note: "Sports medicine reservation" },
    ],
    notes: [
      {
        id: "NOTE-TM-001",
        title: "Maintenance caution",
        type: "Maintenance",
        body: "Keep one treadmill offline until belt tracking is cleared.",
        author: "Sports Medicine",
        createdAt: "2026-05-13",
      },
    ],
    history: [
      "Sep 10, 2025 - Item created with 2 total units.",
      "May 1, 2026 - 1 unit assigned to Nina Mercado.",
      "May 13, 2026 - Sent to maintenance for belt tracking issue.",
    ],
    updatedAt: "2026-05-13",
    archived: false,
  },
  {
    id: "INV-BB-098",
    sku: "ADNU-BB-098",
    name: "Wilson Evolution Basketballs",
    category: "Equipment",
    sport: "Basketball",
    totalQuantity: 18,
    availableQuantity: 3,
    condition: "Good",
    status: "Low Stock",
    location: "Main Equipment Room",
    brand: "Wilson",
    model: "Evolution",
    size: "Official size 7",
    description: "Daily training basketball stock for court sessions, skills work, and small-sided scrimmages.",
    imageUrl: "https://images.unsplash.com/photo-1519861531473-9200262188bf?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Court Supply PH",
      date: "2025-11-18",
      unitCost: 62,
      warranty: "Standard supplier replacement window closed",
    },
    assignments: [
      {
        id: "ASN-BB-001",
        assigneeId: "COACH-001",
        assigneeName: "David Reyes",
        assigneeType: "Coach",
        sport: "Basketball",
        quantity: 10,
        assignedDate: "2026-05-03",
        dueDate: "2026-05-18",
        returnDate: "",
        status: "Active",
        conditionOut: "Good",
        conditionIn: "",
        notes: "Combine week court set.",
      },
      {
        id: "ASN-BB-002",
        assigneeId: "#2022-09114",
        assigneeName: "Marcus Santos",
        assigneeType: "Athlete",
        sport: "Basketball",
        quantity: 5,
        assignedDate: "2026-04-18",
        dueDate: "2026-05-02",
        returnDate: "2026-05-02",
        status: "Returned",
        conditionOut: "Good",
        conditionIn: "Good",
        notes: "Returned after shooting clinic.",
      },
    ],
    maintenanceRecords: [],
    stockMovements: [
      { id: "STK-BB-001", date: "2025-11-18", type: "Stock received", quantity: 18, balance: 18, note: "Initial purchase" },
      { id: "STK-BB-002", date: "2026-05-03", type: "Assigned", quantity: -10, balance: 8, note: "Issued to David Reyes" },
      { id: "STK-BB-003", date: "2026-05-02", type: "Returned", quantity: 5, balance: 13, note: "Returned by Marcus Santos" },
    ],
    notes: [],
    history: [
      "Nov 18, 2025 - Item created with 18 total units.",
      "May 2, 2026 - 5 units returned by Marcus Santos.",
      "May 3, 2026 - 10 units assigned to David Reyes.",
    ],
    updatedAt: "2026-05-12",
    archived: false,
  },
  {
    id: "INV-MED-006",
    sku: "ADNU-MED-006",
    name: "Sideline Medical Kit",
    category: "Medical Supplies",
    sport: "All Athletics",
    totalQuantity: 8,
    availableQuantity: 6,
    condition: "Good",
    status: "Available",
    location: "Sports Medicine Clinic",
    brand: "MedPro",
    model: "Sideline Response Kit",
    size: "Medium kit",
    description: "Portable first-response kit for practices, events, and travel rosters.",
    imageUrl: "https://images.unsplash.com/photo-1584362917165-526a968579e8?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Campus Health Procurement",
      date: "2026-01-22",
      unitCost: 145,
      warranty: "Consumables tracked separately",
    },
    assignments: [],
    maintenanceRecords: [
      {
        id: "MNT-MED-001",
        status: "Good",
        dateReported: "2026-05-10",
        issue: "Consumables audit",
        resolution: "Tape, gauze, and cold packs restocked.",
        cost: 48,
        nextInspectionDate: "2026-06-10",
      },
    ],
    stockMovements: [
      { id: "STK-MED-001", date: "2026-01-22", type: "Stock received", quantity: 8, balance: 8, note: "Initial kit allocation" },
      { id: "STK-MED-002", date: "2026-05-10", type: "Stock adjusted", quantity: -2, balance: 6, note: "Travel kits reserved" },
    ],
    notes: [],
    history: [
      "Jan 22, 2026 - Item created with 8 total units.",
      "May 10, 2026 - Consumables restocked after audit.",
    ],
    updatedAt: "2026-05-10",
    archived: false,
  },
  {
    id: "INV-UNI-017",
    sku: "ADNU-UNI-017",
    name: "Basketball Away Uniform Set",
    category: "Uniforms",
    sport: "Basketball",
    totalQuantity: 16,
    availableQuantity: 0,
    condition: "Fair",
    status: "Assigned",
    location: "Records Office",
    brand: "Adidas",
    model: "Custom away set",
    size: "Mixed roster sizes",
    description: "Away uniform set issued to the men's basketball travel roster.",
    imageUrl: "https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Teamwear Studio",
      date: "2025-08-02",
      unitCost: 54,
      warranty: "Embroidery repair only",
    },
    assignments: [
      {
        id: "ASN-UNI-001",
        assigneeId: "COACH-001",
        assigneeName: "David Reyes",
        assigneeType: "Coach",
        sport: "Basketball",
        quantity: 16,
        assignedDate: "2026-04-28",
        dueDate: "2026-06-02",
        returnDate: "",
        status: "Active",
        conditionOut: "Fair",
        conditionIn: "",
        notes: "Travel roster full set.",
      },
    ],
    maintenanceRecords: [],
    stockMovements: [
      { id: "STK-UNI-001", date: "2025-08-02", type: "Stock received", quantity: 16, balance: 16, note: "Season uniform set" },
      { id: "STK-UNI-002", date: "2026-04-28", type: "Assigned", quantity: -16, balance: 0, note: "Issued to David Reyes" },
    ],
    notes: [
      {
        id: "NOTE-UNI-001",
        title: "Replacement planning",
        type: "Administrative",
        body: "Plan new away set before next school year.",
        author: "Equipment Office",
        createdAt: "2026-05-11",
      },
    ],
    history: [
      "Aug 2, 2025 - Item created with 16 total units.",
      "Apr 28, 2026 - Full set assigned to David Reyes.",
    ],
    updatedAt: "2026-05-11",
    archived: false,
  },
  {
    id: "INV-SOC-212",
    sku: "ADNU-SOC-212",
    name: "Adidas FIFA Pro Match Ball",
    category: "Equipment",
    sport: "Football",
    totalQuantity: 10,
    availableQuantity: 9,
    condition: "Damaged",
    status: "Damaged",
    location: "University Oval Track",
    brand: "Adidas",
    model: "FIFA Pro",
    size: "Official size 5",
    description: "Match ball stock for football training, tryouts, and official game preparation.",
    imageUrl: "https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Pitch Sports Supply",
      date: "2026-03-04",
      unitCost: 92,
      warranty: "Supplier replacement through Sep 2026",
    },
    assignments: [],
    maintenanceRecords: [
      {
        id: "MNT-SOC-001",
        status: "Damaged",
        dateReported: "2026-05-12",
        issue: "One ball split at seam after wet-field training.",
        resolution: "Removed from active match set.",
        cost: 0,
        nextInspectionDate: "2026-05-20",
      },
    ],
    stockMovements: [
      { id: "STK-SOC-001", date: "2026-03-04", type: "Stock received", quantity: 10, balance: 10, note: "Initial purchase" },
      { id: "STK-SOC-002", date: "2026-05-12", type: "Marked damaged", quantity: -1, balance: 9, note: "One ball removed" },
    ],
    notes: [],
    history: [
      "Mar 4, 2026 - Item created with 10 total units.",
      "May 12, 2026 - One unit marked damaged after wet-field training.",
    ],
    updatedAt: "2026-05-12",
    archived: false,
  },
  {
    id: "INV-DOC-003",
    sku: "ADNU-DOC-003",
    name: "Athlete Equipment Waiver Forms",
    category: "Documents/Forms",
    sport: "All Athletics",
    totalQuantity: 120,
    availableQuantity: 120,
    condition: "Excellent",
    status: "Available",
    location: "Records Office",
    brand: "ADNU Athletics",
    model: "2026 waiver packet",
    size: "A4",
    description: "Printed equipment issue and liability forms for athlete and coach sign-off.",
    imageUrl: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Campus Print Office",
      date: "2026-05-01",
      unitCost: 1,
      warranty: "Internal print run",
    },
    assignments: [],
    maintenanceRecords: [],
    stockMovements: [
      { id: "STK-DOC-001", date: "2026-05-01", type: "Stock received", quantity: 120, balance: 120, note: "Printed for summer term" },
    ],
    notes: [],
    history: ["May 1, 2026 - Item created with 120 total forms."],
    updatedAt: "2026-05-14",
    archived: false,
  },
  {
    id: "INV-LOST-004",
    sku: "ADNU-TRK-004",
    name: "Polar H10 Heart Monitor",
    category: "Training Gear",
    sport: "Track & Field",
    totalQuantity: 6,
    availableQuantity: 4,
    condition: "Lost",
    status: "Lost",
    location: "University Oval Track",
    brand: "Polar",
    model: "H10",
    size: "Adjustable strap",
    description: "Heart-rate straps for conditioning tests and monitored return-to-play sessions.",
    imageUrl: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=320&h=240&fit=crop&q=80",
    purchase: {
      vendor: "Performance Lab Systems",
      date: "2025-10-07",
      unitCost: 92,
      warranty: "Device warranty active",
    },
    assignments: [
      {
        id: "ASN-LOST-001",
        assigneeId: "#2021-08422",
        assigneeName: "Sarah Jenkins",
        assigneeType: "Athlete",
        sport: "Track & Field",
        quantity: 1,
        assignedDate: "2026-04-28",
        dueDate: "2026-05-12",
        returnDate: "",
        status: "Lost",
        conditionOut: "Good",
        conditionIn: "Lost",
        notes: "Missing after regional qualifier travel.",
      },
    ],
    maintenanceRecords: [],
    stockMovements: [
      { id: "STK-LOST-001", date: "2025-10-07", type: "Stock received", quantity: 6, balance: 6, note: "Initial purchase" },
      { id: "STK-LOST-002", date: "2026-05-12", type: "Marked lost", quantity: -1, balance: 5, note: "Travel loss report" },
    ],
    notes: [
      {
        id: "NOTE-LOST-001",
        title: "Loss follow-up",
        type: "Administrative",
        body: "Confirm whether device was packed with track travel equipment.",
        author: "Equipment Office",
        createdAt: "2026-05-12",
      },
    ],
    history: [
      "Oct 7, 2025 - Item created with 6 total units.",
      "May 12, 2026 - One monitor marked lost after travel report.",
    ],
    updatedAt: "2026-05-12",
    archived: false,
  },
];

export function createInventoryItemFromForm(values) {
  const id = `INV-${String(Date.now()).slice(-6)}`;
  const quantity = Number(values.totalQuantity || 0);
  const available = Number(values.availableQuantity || 0);
  const now = todayIso();

  return {
    id,
    sku: values.sku.trim(),
    name: values.name.trim(),
    category: values.category,
    sport: values.sport,
    totalQuantity: quantity,
    availableQuantity: available,
    condition: values.condition,
    status: values.status,
    location: values.location,
    brand: values.brand.trim(),
    model: values.model.trim(),
    size: values.size.trim(),
    description:
      values.description.trim() ||
      "New inventory item created locally. Staff can complete details before backend persistence is connected.",
    imageUrl: `https://source.unsplash.com/320x240/?sports,equipment&sig=${encodeURIComponent(id)}`,
    purchase: {
      vendor: values.vendor.trim(),
      date: values.purchaseDate,
      unitCost: values.unitCost ? Number(values.unitCost) : "",
      warranty: "Pending",
    },
    assignments: [],
    maintenanceRecords: [],
    stockMovements: [
      {
        id: `STK-${Date.now()}`,
        date: now,
        type: "Stock received",
        quantity,
        balance: available,
        note: "Created locally",
      },
    ],
    notes: values.notes.trim()
      ? [
          {
            id: `NOTE-${Date.now()}`,
            title: "Initial note",
            type: "Administrative",
            body: values.notes.trim(),
            author: "Athletics Staff",
            createdAt: now,
          },
        ]
      : [],
    history: [`${new Date().toLocaleDateString()} - Item created locally with ${quantity} total units.`],
    updatedAt: now,
    archived: false,
  };
}

export function inventoryItemToForm(item) {
  return {
    ...emptyInventoryForm,
    name: item.name,
    sku: item.sku,
    category: item.category,
    sport: item.sport,
    totalQuantity: String(item.totalQuantity),
    availableQuantity: String(item.availableQuantity),
    condition: item.condition,
    status: item.status,
    location: item.location,
    brand: item.brand ?? "",
    model: item.model ?? "",
    size: item.size ?? "",
    description: item.description ?? "",
    vendor: item.purchase?.vendor ?? "",
    purchaseDate: item.purchase?.date ?? "",
    unitCost: item.purchase?.unitCost ? String(item.purchase.unitCost) : "",
    notes: "",
  };
}

export function mergeInventoryItemForm(item, values) {
  return {
    ...item,
    sku: values.sku.trim(),
    name: values.name.trim(),
    category: values.category,
    sport: values.sport,
    totalQuantity: Number(values.totalQuantity || 0),
    availableQuantity: Number(values.availableQuantity || 0),
    condition: values.condition,
    status: values.status,
    location: values.location,
    brand: values.brand.trim(),
    model: values.model.trim(),
    size: values.size.trim(),
    description: values.description.trim(),
    purchase: {
      ...item.purchase,
      vendor: values.vendor.trim(),
      date: values.purchaseDate,
      unitCost: values.unitCost ? Number(values.unitCost) : "",
    },
  };
}
