import {
  Archive,
  CalendarDays,
  Download,
  Eye,
  FileText,
  PencilLine,
  Plus,
  ShieldCheck,
  StickyNote,
  Trash2,
  Upload,
  UserMinus,
  UserPlus,
  Users,
  Package,
  Undo2,
} from "lucide-react";

export const actionIcons = {
  add: Plus,
  addNote: StickyNote,
  archive: Archive,
  assign: UserPlus,
  deactivate: UserMinus,
  delete: Trash2,
  download: Download,
  edit: PencilLine,
  manageAthletes: Users,
  manageDocuments: FileText,
  manageGear: Package,
  remove: UserMinus,
  upload: Upload,
  view: Eye,
  viewDetails: Eye,
  viewSchedule: CalendarDays,
  updateStatus: ShieldCheck,
  markReturned: Undo2,
};
